### ISSUE TITLE
Add option to remove date/time column

### ISSUE THREAD

**Issue by Gitoffthelawn** [program-in-chinese/HistoryInThreads_WebExtension#10]
It takes up too much room!

**Comment by nobodxbodon** [comment]
Sorry about the very late update, but I've removed the column and shown the date/time as the title of each link in version 2.3.1. Hope it helps.

**Comment by Gitoffthelawn** [comment]
Thanks!  I'll take a look.  :)

**Comment by Gitoffthelawn** [comment]
That looks great!  Thank you!

**Comment by hmijail** [comment]
I was about to add a feature request to have the date/time as an extra column, so I am surprised to find that this already existed and was removed! It would be great to have it as an option :)

**Comment by nobodxbodon** [comment]
@hmijail thanks for the review and willingness to contribute.
I use this extension very occasionally these days, so I'm a bit reluctant to study the new UI and refresh my memory at the moment.
I'd very appreciate a PR certainly.
