### ISSUE TITLE
Date/time column is misaligned for some locales

### ISSUE THREAD

**Issue by Gitoffthelawn** [program-in-chinese/HistoryInThreads_WebExtension#11]
For some locales, the date/time column is misaligned: the padding is on the right, but needs to be on the left.

**Comment by nobodxbodon** [comment]
Thanks for the report. May I ask if you could give an locale withe the issue please?

**Comment by Gitoffthelawn** [comment]
You're welcome.  I tested several popular English locales, and they all had the issue.

**Comment by nobodxbodon** [comment]
The column is removed in the workaround update for #10.
