### ISSUE TITLE
Can't access

### ISSUE THREAD

**Issue by segunolulana** [program-in-chinese/HistoryInThreads_WebExtension#13]
The addon stopped working after the webextension update. I could access the page before with chrome://history_in_threads/content/historyinthreads.xul but I can't even access it from anywhere again even from the sidebar

**Comment by nobodxbodon** [comment]
Thanks for the report. May I ask your Firefox version and system info? I just tested in FF 55.0.3 (64bit) under Mac and it's in sidebar menu:
![screen shot 2017-09-12 at 7 25 43 am](https://user-images.githubusercontent.com/392497/30332713-e4a19894-978f-11e7-9167-22de3da49ebb.png)

**Comment by segunolulana** [comment]
@nobodxbodon I'm using Firefox 52.0.2 ESR on Windows 8.1

**Comment by nobodxbodon** [comment]
Sorry to hear that! I just tested with 54.0.1 and it seems to work. If there's no particular reason that prevents you from updating, could you please try updating to latest FF version?
Thanks again.

**Comment by segunolulana** [comment]
I kind of prefer using Firefox ESR

**Comment by nobodxbodon** [comment]
I hope it works in ESR 60 now.
