### ISSUE TITLE
Can't read root node titles

### ISSUE THREAD

**Issue by winny-** [program-in-chinese/HistoryInThreads_WebExtension#14]
![2018-05-18-184354_488x94](https://user-images.githubusercontent.com/3893828/40262223-71e92be6-5acb-11e8-9061-149578b40e2d.png)

I am using a dark theme in firefox, and a dark system theme, if it matters :)

**Comment by nobodxbodon** [comment]
May I ask if it happens to all the root nodes? As I vaguely recall some URL redirections can have empty title, and according to the timestamp it only took 1 sec before opening the child page, so it could be the case.
Or could you share the url of that root node, if you can recall? Pitifully there's no 'export' feature.

**Comment by winny-** [comment]
It looks like these root nodes represent `about:home` and the first successor that shows a title is the website I visited by clicking on a tile. Let me know if I can get you any other information :)

**Comment by nobodxbodon** [comment]
Sorry for the delay. In latest version 2.2, when the title is empty, the url is displayed instead.

**Comment by nobodxbodon** [comment]
Please let me know or reopen the issue if there's still problem. Thanks.
