### ISSUE TITLE
界面字符串多语言支持

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/HistoryInThreads_WebExtension#3]
现在还是全中文. [mdn Internationalization文档](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization)

**Comment by nobodxbodon** [comment]
根据https://discourse.mozilla.org/t/we-i18n-could-use-a-getaddonlanguage-function/14982, 侧栏的多语言支持有限. 决定暂时用全英文界面, 由于50%的用户用的是英文版火狐.

**Comment by yfdyh000** [comment]
对于html元素，以ID或其他方式获取元素然后`i18n.getMessage`赋值是目前的主流方法，Chrome扩展也如此。

**Comment by nobodxbodon** [comment]
多谢! 其实之前试了在sidebar/main.js开头加这个:
```
  $("#选择时间范围 option[value='今天']").text = "yeahaha";   <--- 这个没用
  $("#keywords").val("dddddd");  <--- 这个有用
```
不知为何. 于是就找到之前的链接, 就以为是有某种限制了.

**Comment by yfdyh000** [comment]
innerText/innerHTML/textContent 等可用。.text 是别的属性。

**Comment by nobodxbodon** [comment]
多谢, 不然就放弃了. 后来发现用`.text('...')`就行了, 太久没碰jquery了 :) 
已经提交2.0, 等待审核~. 用的老dynatree可能需要完整版, 搞不好通不过...
